version: "3.5"
services:

  api01: &api
    build: ./Rinha2024
    hostname: api01
    environment:
      - API_PORT=80
      - DB_CONNECTION="Host=localhost;Database=Rinha;Username=postgres;Password=123456"

    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "165MB"

networks:
  rinha-network:
    driver: bridge